### ISSUE TITLE
Question regarding evaluation process

### ISSUE THREAD

**Issue by chohj1111** [WinstonHuTiger/BraSyn_tutorial#1]
Firstly, thank you for providing the code related to the Brasyn challenge. While running the code, I have a question about measuring SSIM, specifically regarding the range of data values.

Should both array_real and array_syn, that is, GT and output, be in an unnormalized state? If not, the process of percentile clipping seems a bit unusual to me.

Additionally, I am curious about the reason why the prediction value is multiplied by two at [line 66](https://github.com/hongweilibran/BraSyn/blob/294ae5932bb2f2a9cc4384150abf0de46b89e3e9/ssim.py#L66) in ssim.py.

Thank you .

**Comment by chohj1111** [comment]
> Firstly, thank you for providing the code related to the Brasyn challenge. While running the code, I have a question about measuring SSIM, specifically regarding the range of data values.
> 
> Should both array_real and array_syn, that is, GT and output, be in an unnormalized state? If not, the process of percentile clipping seems a bit unusual to me.
> 
> Additionally, I am curious about the reason why the prediction value is multiplied by two at [line 66](https://github.com/hongweilibran/BraSyn/blob/294ae5932bb2f2a9cc4384150abf0de46b89e3e9/ssim.py#L66) in ssim.py.
> 
> Thank you .

I understand that this repository might not be directly related, but I wanted to post my issue here to ensure it is not overlooked. 
Apologies if this causes any inconvenience.

**Comment by WinstonHuTiger** [comment]
> Firstly, thank you for providing the code related to the Brasyn challenge. While running the code, I have a question about measuring SSIM, specifically regarding the range of data values.
> 
> Should both array_real and array_syn, that is, GT and output, be in an unnormalized state? If not, the process of percentile clipping seems a bit unusual to me.
> 
> Additionally, I am curious about the reason why the prediction value is multiplied by two at [line 66](https://github.com/hongweilibran/BraSyn/blob/294ae5932bb2f2a9cc4384150abf0de46b89e3e9/ssim.py#L66) in ssim.py.
> 
> Thank you .

Hi, thank you for reaching out. From my understanding, SSIM can be calculated after normalization. [For this line here](https://github.com/hongweilibran/BraSyn/blob/294ae5932bb2f2a9cc4384150abf0de46b89e3e9/ssim.py#L66), from our previous experiment, it does not really matter, but it could be a mistake. 

I hope my explanation helps you a little bit.

**Comment by chohj1111** [comment]
Thank you for the quick response. I will close the issue.
