### ISSUE TITLE
Did the pretrained weight come from the Brasyn 2024 dataset? (aka Brasyn 2023 dataset)

### ISSUE THREAD

**Issue by Guoweiyan** [WinstonHuTiger/BraSyn_tutorial#2]
Hi, thanks for your sharing!
Did the **pretrained weight come from the Brasyn 2024 dataset** ? [Brasyn 2024](https://www.synapse.org/Synapse:syn60263602)?

sincerely,
weiyan

**Comment by WinstonHuTiger** [comment]
If you are referring to the generative baseline model, the answer is yes, since the datasets from 2023 and 2024 have no difference. The pre-trained nnunet for evaluation is trained on Brats 2021 dataset.

**Comment by Guoweiyan** [comment]
Sorry to bother more, but can you provide your preprocessing-related information ( such as zscore or not)? 
I just do zscore to the dataset and test the pretrained model's performance, it shows a bad psnr of around 25db and ssim lower than 0.2.
I'm not sure if I have done something destructive :)
Thanks a lot!

sincerely,
weiyan
![image](https://github.com/WinstonHuTiger/BraSyn_tutorial/assets/31952716/f7a445ce-cfcb-41f9-a9d8-88f7423d9d42)

**Comment by WinstonHuTiger** [comment]
> Sorry to bother more, but can you provide your preprocessing-related information ( such as zscore or not)? I just do zscore to the dataset and test the pretrained model's performance, it shows a bad psnr of around 25db and ssim lower than 0.2. I'm not sure if I have done something destructive :) Thanks a lot!
> 
> sincerely, weiyan ![image](https://private-user-images.githubusercontent.com/31952716/347471257-f7a445ce-cfcb-41f9-a9d8-88f7423d9d42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2Mjc0ODQsIm5iZiI6MTcyMDYyNzE4NCwicGF0aCI6Ii8zMTk1MjcxNi8zNDc0NzEyNTctZjdhNDQ1Y2UtY2ZjYi00MWY5LWE5ZDgtODhmNzQyM2Q5ZDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE1NTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ODgzZmYzMmI2NWMzMWM4MTU4MWJlMjJmYzBkYmYwYmQwNmExM2MzOTZkOTIwNDY5MGY2MzQ4OTI0ODk4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6KI0pWKixQejOWS7JOdC60h7w_I_FiEisGwHeb_ZDc)

It is all included in the  [data loader](https://github.com/WinstonHuTiger/BraSyn_tutorial/blob/main/project/data/brain_3D_random_mod_dataset.py) and I did not do any pre-processing to the dataset (z-score is not used). More especially, you can check them here:

```python=
transformations = [
            transforms.Lambda(lambda x: getBetterOrientation(x, "IPL")),
            transforms.Lambda(lambda x: np.array(x.get_fdata())[np.newaxis, ...]),
            # transforms.Lambda(lambda x: sk_trans.resize(x, (256, 256, 160), order = 1, preserve_range=True)),
            # image size [1, 160, 240, 240]
            transforms.Lambda(lambda x: x[:,8:152,24:216,24:216]),
            # transforms.Lambda(lambda x: resize(x, (x.shape[0],), order=1, anti_aliasing=True)),
            transforms.Lambda(lambda x: toGrayScale(x)),
            transforms.Lambda(lambda x: torch.tensor(x, dtype=torch.float16 if opt.amp else torch.float32)),
            # transforms.Resize((256, 256)),
            PadIfNecessary(3),
        ]
```

**Comment by Guoweiyan** [comment]
I am deeply grateful to you. ❤️

**Comment by WinstonHuTiger** [comment]
Then I can close this issue.
